import type { ProviderDef } from './types.js'

const providers: ProviderDef[] = [
  {
    id: 'openai',
    label: 'OpenAI',
    hint: 'GPT-4o, o3, etc.',
    authKind: 'api_key',
    envKeys: ['OPENAI_API_KEY'],
    defaultModel: 'gpt-4o-mini',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'o3', 'o3-mini', 'o4-mini', 'gpt-5.2'],
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    hint: 'Claude Opus, Sonnet',
    authKind: 'api_key',
    envKeys: ['ANTHROPIC_API_KEY'],
    baseUrl: 'https://api.anthropic.com/v1/',
    defaultModel: 'claude-sonnet-4-20250514',
    models: ['claude-opus-4-20250514', 'claude-sonnet-4-20250514', 'claude-haiku-3-20250514', 'claude-3.5-sonnet-latest'],
  },
  {
    id: 'gemini',
    label: 'Google Gemini',
    hint: 'Gemini 2.5 Pro, Flash',
    authKind: 'api_key',
    envKeys: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'],
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    defaultModel: 'gemini-2.5-flash',
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-2.0-flash-lite'],
  },
  {
    id: 'codex',
    label: 'ChatGPT / Codex',
    hint: 'Browser OAuth (no API key needed)',
    authKind: 'oauth',
    envKeys: [],
    defaultModel: 'gpt-5.2',
    models: ['gpt-5.2', 'gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'o3', 'o3-mini', 'o4-mini'],
  },
  {
    id: 'ollama',
    label: 'Ollama (local)',
    hint: 'Self-hosted, no auth',
    authKind: 'none',
    envKeys: [],
    baseUrl: 'http://localhost:11434/v1/',
    defaultModel: 'llama3',
    models: ['llama3', 'llama3.3', 'llama3.1', 'qwen2.5', 'deepseek-r1', 'gemma2', 'phi3', 'mistral'],
  },
  {
    id: 'openai-compat',
    label: 'OpenAI-compatible',
    hint: 'Custom endpoint (LM Studio, vLLM, etc.)',
    authKind: 'api_key',
    envKeys: ['OPENAI_COMPAT_API_KEY'],
    defaultModel: 'default',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    hint: 'DeepSeek-V3, R1',
    authKind: 'api_key',
    envKeys: ['DEEPSEEK_API_KEY'],
    baseUrl: 'https://api.deepseek.com/v1/',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'groq',
    label: 'Groq',
    hint: 'Fast inference: Llama, Mixtral',
    authKind: 'api_key',
    envKeys: ['GROQ_API_KEY'],
    baseUrl: 'https://api.groq.com/openai/v1/',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
  },
  {
    id: 'together',
    label: 'Together AI',
    hint: 'Open-source models',
    authKind: 'api_key',
    envKeys: ['TOGETHER_API_KEY'],
    baseUrl: 'https://api.together.xyz/v1/',
    defaultModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    models: [
      'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      'mistralai/Mixtral-8x22B-Instruct-v0.1',
      'Qwen/Qwen2.5-72B-Instruct-Turbo',
    ],
  },
  {
    id: 'mistral',
    label: 'Mistral AI',
    hint: 'Mistral Large, Codestral',
    authKind: 'api_key',
    envKeys: ['MISTRAL_API_KEY'],
    baseUrl: 'https://api.mistral.ai/v1/',
    defaultModel: 'mistral-large-latest',
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest'],
  },
  {
    id: 'xai',
    label: 'xAI',
    hint: 'Grok',
    authKind: 'api_key',
    envKeys: ['XAI_API_KEY'],
    baseUrl: 'https://api.x.ai/v1/',
    defaultModel: 'grok-3-mini',
    models: ['grok-3', 'grok-3-mini', 'grok-3-fast'],
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    hint: 'Multi-model gateway',
    authKind: 'api_key',
    envKeys: ['OPENROUTER_API_KEY'],
    baseUrl: 'https://openrouter.ai/api/v1/',
    defaultModel: 'openai/gpt-4o-mini',
    models: [
      'openai/gpt-4o-mini',
      'openai/gpt-4o',
      'anthropic/claude-sonnet-4',
      'google/gemini-2.5-flash',
      'meta-llama/llama-3.1-70b-instruct',
    ],
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    hint: 'MiniMax models',
    authKind: 'api_key',
    envKeys: ['MINIMAX_API_KEY'],
    baseUrl: 'https://api.minimax.chat/v1/',
    defaultModel: 'MiniMax-M1',
    models: ['MiniMax-M1', 'MiniMax-M1-40k'],
  },
]

export function getAllProviders(): ProviderDef[] {
  return providers
}

export function getProvider(id: string): ProviderDef | undefined {
  return providers.find((p) => p.id === id)
}
